#!/bin/zsh

# to do, remove adding readme.md to the readme.md files!

echo building readme files for assets...

for dir in assets/*; do
    echo "" > $dir/readme.md
    for file in $dir/*
        echo "<img src=\"""${file##*/}"\"\> >> $dir/readme.md
done

echo built!
