#!/bin/zsh

echo "it works"

# to do
# generate the html page, divs, and distance styling (not styles) you see in index.html via this script

echo "" > images.html

TODAY=$(date "+%s")
SCALE=10

for IMAGE in images/*; do
  HOUR=$(date -r $IMAGE "+%H-%M-%S") 
  DAY=$(date -r $IMAGE "+%Y-%m-%d")
  CREATION=$(date -r $IMAGE "+%s")
  DIFFERENCE=$(( $TODAY - $CREATION ))
  DIST=$(( $DIFFERENCE / $SCALE ))
  echo "<p style=\"position: absolute; top: $(($DIST))px\">$DAY $HOUR</p>" >> images.html
  echo "<img src=\"$IMAGE\" style=\"max-width:150px; position:relative; top: $(($DIST))px;\">" >> images.html
done;